backend:
  name: git-gateway
  branch: main # 如果你的分支叫 master，請改為 master

media_folder: "assets/uploads" # 圖片上傳位置
public_folder: "/assets/uploads"

# 這裡定義後台可以編輯什麼
collections:
  - name: "blog"
    label: "文章"
    folder: "_posts" # 文章存放在 GitHub 的路徑
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # 編輯器欄位
      - {label: "版型", name: "layout", widget: "hidden", default: "post"}
      - {label: "標題", name: "title", widget: "string"}
      - {label: "發布日期", name: "date", widget: "datetime"}
      - {label: "內文", name: "body", widget: "markdown"}
